version: "3.1"

services:
  stochss-compute:
    depends_on:
      - "scheduler"
      - "worker"
    # image: stochss/stochss-compute
    image: sssc
    volumes:
      - "./sd-cache/:/usr/src/app/sd-cache/"
    ports:
      - "29681:29681"
    command: ["python", "app.py", "--host", "0.0.0.0", "--daskhost", "scheduler"]

  scheduler:
    image: ghcr.io/dask/dask:latest
    hostname: scheduler
    volumes:
      - "./sd-cache/:/sd-cache/"
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: ghcr.io/dask/dask:latest
    environment:
      - EXTRA_PIP_PACKAGES=stochss_compute
    volumes:
      - "./sd-cache/:/sd-cache/"
    command: ["dask-worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    deploy:
      replicas: 2

volumes: 
  sd-cache: {}

