version: "3.1"

services:
  stochss-compute:
    image: stochss/stochss-compute
    ports:
      - "29681:29681"
      
  scheduler:
    image: ghcr.io/dask/dask:latest
    # hostname: scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]

  worker:
    image: ghcr.io/dask/dask:latest
    command: ["dask-worker", "tcp://scheduler:8786"]
    # For Docker swarm you can specify multiple workers, this is ignored by `docker-compose up`
    deploy:
      replicas: 2

