apiVersion: apps/v1
kind: Deployment
metadata:
  name: dask
spec:
  selector:
    matchLabels:
      app: dask
  template:
    metadata:
      labels:
        app: dask
    spec:
      containers:
      - name: dask-scheduler
        image: daskdev/dask
        imagePullPolicy: IfNotPresent
        args: [dask-scheduler, --host, localhost]
        ports:
        - containerPort: 8786
        resources:
          limits:
            cpu: "2"
            memory: 6G
          requests:
            cpu: "2"
            memory: 6G
      - name: dask-worker
        image: daskdev/dask
        imagePullPolicy: IfNotPresent
        args: [dask-worker, localhost:8786]
        ports:
        - containerPort: 8786
        resources:
          limits:
            cpu: "2"
            memory: 6G
          requests:
            cpu: "2"
            memory: 6G
---
apiVersion: v1
kind: Service
metadata:
  name: dask-service
spec:
  selector:
    app: dask
  ports:
  - port: 8786
    targetPort: 8786

