#!/usr/bin/env python
from stochss_compute.server.api import start_api
import asyncio
from argparse import ArgumentParser, Namespace


def parse_args() -> Namespace:
    desc = '''
        StochSS-Compute is a server and cache that anonymizes StochSS simulation data.
    '''
    parser = ArgumentParser(description=desc, add_help=True, conflict_handler='resolve')

    server = parser.add_argument_group('Server')
    # server.add_argument("-h", "--host", default='127.0.0.1', required=False,
    #                     help="The host to use for the flask server. Defaults to localhost.")
    server.add_argument("-p", "--port", default=29681, type=int, required=False,
                        help="The port to use for the server. Defaults to 29681.")

    cache = parser.add_argument_group('Cache')
    cache.add_argument('-c', '--cache', default='cache/', required=False, help='Path to use for the cache.')

    dask = parser.add_argument_group('Dask')
    dask.add_argument("-H", "--dask-host", default='localhost', required=False,
                        help="The host to use for the dask scheduler. Defaults to localhost.")
    dask.add_argument("-P", "--dask-scheduler-port", default=8786, type=int, required=False,
                        help="The port to use for the dask scheduler. Defaults to 8786.")
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    print(args.__dict__)
    asyncio.run(start_api(**args.__dict__))