name: pylint

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Python Pylint GitHub Action
      uses: fylein/python-pylint-github-action@v1
      with:
        args: pip3 install -r requirements.txt && pylint --rcfile=.pylintrc stochss-compute
  #   - name: Set up Python ${{ matrix.python-version }}
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: ${{ matrix.python-version }}
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       python -m pip install .
  #   - name: Run integration tests
  #     run: |
  #       cd test
  #       python run_integration_tests.py
  #   - name: Run unit tests
  #     run: |
  #       cd test
  #       python run_unit_tests.py